imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ['channel_ex1']
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type: rotating_file
            max_files: 3
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  error
        second:
            type: rotating_file
            max_files: 3
            path:   "%kernel.logs_dir%/channel_ex1/%kernel.environment%.log"
            level:  error
            channels: ['channel_ex1']
