monolog:
    handlers:
        exercise4:
            type: rotating_file
            max_files: 1
            path:   "%kernel.logs_dir%/channel_ex4/%kernel.environment%.log"
            level:  error
            channels: ['channel_ex4']
            formatter: formatter.leet

