services:
    processor.git:
        class: Monolog\Processor\GitProcessor
        tags:
            - { name: monolog.processor, method: __invoke, handler: 'exercise5' }

    exercice2.processor:
        class: AppBundle\Services\MachineNameProcessor
        arguments:
            - '@exercise2.service'
        tags:
#            - { name: monolog.processor, method: gattai, channel: 'channel_ex2' }
            - { name: monolog.processor, method: gattai, handler: 'exercise5' }

