imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: ['channel_ex1']
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type: rotating_file
            max_files: 3
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  error

        exercise1:
            type: rotating_file
            max_files: 3
            path:   "%kernel.logs_dir%/channel_ex1/%kernel.environment%.log"
            level:  error
            channels: ['channel_ex1']
        exercise2:
            type: rotating_file
            max_files: 1
            path:   "%kernel.logs_dir%/channel_ex2/%kernel.environment%.log"
            level:  error
            channels: ['channel_ex2']
        exercise3:
            type: service
            id: 'handler.forgetfull'
        exercise4:
            type: rotating_file
            max_files: 1
            path:   "%kernel.logs_dir%/channel_ex4/%kernel.environment%.log"
            level:  error
            channels: ['channel_ex4']
            formatter: formatter.leet
        exercise5:
            type: rotating_file
            max_files: 1
            path:   "%kernel.logs_dir%/channel_ex5/%kernel.environment%.log"
            level:  error
            channels: ['channel_ex5']

